package main

import (
	"context"
	"fmt"
	"log"
	"math/big"
	"net/http"
	"os"

	calc "github.com/GoncuCagatay/calc-service/gen/calc"
	calcsvr "github.com/GoncuCagatay/calc-service/gen/http/calc/server"
	goahttp "goa.design/goa/v3/http"
)

// Implements the calc.Service interface generated by Goa
type calcService struct{}

func (s *calcService) Add(ctx context.Context, p *calc.AddPayload) (string, error) {
	a := new(big.Int)
	b := new(big.Int)
	if _, ok := a.SetString(p.A, 10); !ok {
		return "", fmt.Errorf("invalid value for 'a'")
	}
	if _, ok := b.SetString(p.B, 10); !ok {
		return "", fmt.Errorf("invalid value for 'b'")
	}
	result := new(big.Int).Add(a, b)
	log.Printf("Add → a: %s, b: %s, result: %s", a, b, result)
	return fmt.Sprintf("First operand: %s\nSecond operand: %s\nResult: %s", a, b, result), nil
}

func (s *calcService) Subtract(ctx context.Context, p *calc.SubtractPayload) (string, error) {
	a := new(big.Int)
	b := new(big.Int)
	if _, ok := a.SetString(p.A, 10); !ok {
		return "", fmt.Errorf("invalid value for 'a'")
	}
	if _, ok := b.SetString(p.B, 10); !ok {
		return "", fmt.Errorf("invalid value for 'b'")
	}
	result := new(big.Int).Sub(a, b)
	log.Printf("Subtract → a: %s, b: %s, result: %s", a, b, result)
	return fmt.Sprintf("First operand: %s\nSecond operand: %s\nResult: %s", a, b, result), nil
}

type statusCode int

func (s statusCode) StatusCode() int {
	return int(s)
}

func main() {
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	svc := &calcService{}
	endpoints := calc.NewEndpoints(svc)

	mux := goahttp.NewMuxer()
	dec := goahttp.RequestDecoder
	enc := goahttp.ResponseEncoder

	eh := func(ctx context.Context, w http.ResponseWriter, err error) {
		log.Printf("internal error: %v", err)
		w.WriteHeader(http.StatusInternalServerError)
		w.Write([]byte("internal server error"))
	}
	st := func(ctx context.Context, err error) goahttp.Statuser {
		return statusCode(http.StatusInternalServerError)
	}

	calcsvr.Mount(mux, calcsvr.New(endpoints, mux, dec, enc, eh, st))

	log.Printf("Listening on port %s", port)
	log.Fatal(http.ListenAndServe(":"+port, mux))
}
