openapi: 3.0.3
info:
    title: Calculator Service
    description: A simple calculator service
    version: 0.0.1
servers:
    - url: http://localhost:8080
paths:
    /add/{a}/{b}:
        get:
            tags:
                - calc
            summary: add calc
            description: Adds two integes and returns the result.
            operationId: calc#add
            parameters:
                - name: a
                  in: path
                  required: true
                  schema:
                    type: integer
                    example: 1086137054
                    format: int64
                  example: 527538563
                - name: b
                  in: path
                  required: true
                  schema:
                    type: integer
                    example: 2135143470
                    format: int64
                  example: 885860479
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: integer
                                example: 805352709
                                format: int64
                            example: 242624345
components: {}
tags:
    - name: calc
      description: The calc service provides addition.
