openapi: 3.0.3
info:
    title: Calculator Service
    description: A simple calculator service
    version: 0.0.1
servers:
    - url: http://localhost:8080
paths:
    /add/{a}/{b}:
        get:
            tags:
                - calc
            summary: add calc
            operationId: calc#add
            parameters:
                - name: a
                  in: path
                  description: First Operand
                  required: true
                  schema:
                    type: string
                    description: First Operand
                    example: Odit non.
                  example: Et facere aperiam ut rerum ipsam.
                - name: b
                  in: path
                  description: Second Operand
                  required: true
                  schema:
                    type: string
                    description: Second Operand
                    example: Consequatur omnis velit.
                  example: Unde omnis.
            responses:
                "200":
                    description: OK response.
                    content:
                        text/plain:
                            schema:
                                type: string
                                example: Iure repellat.
                            example: Qui mollitia.
    /sub/{a}/{b}:
        get:
            tags:
                - calc
            summary: subtract calc
            description: Subtracts two integers and returns the result.
            operationId: calc#subtract
            parameters:
                - name: a
                  in: path
                  description: First Operand
                  required: true
                  schema:
                    type: string
                    description: First Operand
                    example: Quis consectetur voluptas.
                  example: Neque consequatur maiores aut.
                - name: b
                  in: path
                  description: Second Operand
                  required: true
                  schema:
                    type: string
                    description: Second Operand
                    example: Et consequatur quis dolorum corporis officiis rerum.
                  example: Quia dolores consequatur cum itaque.
            responses:
                "200":
                    description: OK response.
                    content:
                        text/plain:
                            schema:
                                type: string
                                example: Culpa odit.
                            example: Nam deserunt et tempora atque.
components: {}
tags:
    - name: calc
      description: The calc service provides addition.
