openapi: 3.0.3
info:
    title: Calculator Service
    description: A simple calculator service
    version: 0.0.1
servers:
    - url: http://localhost:8080
paths:
    /add/{a}/{b}:
        get:
            tags:
                - calc
            summary: add calc
            description: Adds two integers and returns the result.
            operationId: calc#add
            parameters:
                - name: a
                  in: path
                  description: First Operand
                  required: true
                  schema:
                    type: integer
                    description: First Operand
                    example: 5855163322465186600
                    format: int64
                  example: 1385266597691519195
                - name: b
                  in: path
                  description: Second Operand
                  required: true
                  schema:
                    type: integer
                    description: Second Operand
                    example: 686605435966370186
                    format: int64
                  example: 8228676432890045784
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: integer
                                example: 1698882017578366363
                                format: int64
                            example: 5308928064408640979
    /sub/{a}/{b}:
        get:
            tags:
                - calc
            summary: subtract calc
            description: Subtracts two integers and returns the result.
            operationId: calc#subtract
            parameters:
                - name: a
                  in: path
                  required: true
                  schema:
                    type: integer
                    example: 1016925590796087323
                    format: int64
                  example: 7309877832173772408
                - name: b
                  in: path
                  required: true
                  schema:
                    type: integer
                    example: 3237209857320107068
                    format: int64
                  example: 1228682945796019344
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: integer
                                example: 6747375795581831989
                                format: int64
                            example: 4886963557863946648
components: {}
tags:
    - name: calc
      description: The calc service provides addition.
